# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/raoxue/Documents/cbmc_verifed_juliet_test_case_ground_truth_new/libsox-sox-14.4.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/raoxue/Documents/cbmc_verifed_juliet_test_case_ground_truth_new/libsox-sox-14.4.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raoxue/Documents/cbmc_verifed_juliet_test_case_ground_truth_new/libsox-sox-14.4.2/CMakeFiles /home/raoxue/Documents/cbmc_verifed_juliet_test_case_ground_truth_new/libsox-sox-14.4.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/raoxue/Documents/cbmc_verifed_juliet_test_case_ground_truth_new/libsox-sox-14.4.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tags

# Build rule for target.
tags: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tags
.PHONY : tags

# fast build rule for target.
tags/fast:
	$(MAKE) -f src/CMakeFiles/tags.dir/build.make src/CMakeFiles/tags.dir/build
.PHONY : tags/fast

#=============================================================================
# Target rules for targets named libsox

# Build rule for target.
libsox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsox
.PHONY : libsox

# fast build rule for target.
libsox/fast:
	$(MAKE) -f src/CMakeFiles/libsox.dir/build.make src/CMakeFiles/libsox.dir/build
.PHONY : libsox/fast

#=============================================================================
# Target rules for targets named sox

# Build rule for target.
sox: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sox
.PHONY : sox

# fast build rule for target.
sox/fast:
	$(MAKE) -f src/CMakeFiles/sox.dir/build.make src/CMakeFiles/sox.dir/build
.PHONY : sox/fast

#=============================================================================
# Target rules for targets named rec

# Build rule for target.
rec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rec
.PHONY : rec

# fast build rule for target.
rec/fast:
	$(MAKE) -f src/CMakeFiles/rec.dir/build.make src/CMakeFiles/rec.dir/build
.PHONY : rec/fast

#=============================================================================
# Target rules for targets named sox_sample_test

# Build rule for target.
sox_sample_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sox_sample_test
.PHONY : sox_sample_test

# fast build rule for target.
sox_sample_test/fast:
	$(MAKE) -f src/CMakeFiles/sox_sample_test.dir/build.make src/CMakeFiles/sox_sample_test.dir/build
.PHONY : sox_sample_test/fast

#=============================================================================
# Target rules for targets named example0

# Build rule for target.
example0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example0
.PHONY : example0

# fast build rule for target.
example0/fast:
	$(MAKE) -f src/CMakeFiles/example0.dir/build.make src/CMakeFiles/example0.dir/build
.PHONY : example0/fast

#=============================================================================
# Target rules for targets named example3

# Build rule for target.
example3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example3
.PHONY : example3

# fast build rule for target.
example3/fast:
	$(MAKE) -f src/CMakeFiles/example3.dir/build.make src/CMakeFiles/example3.dir/build
.PHONY : example3/fast

#=============================================================================
# Target rules for targets named example1

# Build rule for target.
example1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example1
.PHONY : example1

# fast build rule for target.
example1/fast:
	$(MAKE) -f src/CMakeFiles/example1.dir/build.make src/CMakeFiles/example1.dir/build
.PHONY : example1/fast

#=============================================================================
# Target rules for targets named example5

# Build rule for target.
example5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example5
.PHONY : example5

# fast build rule for target.
example5/fast:
	$(MAKE) -f src/CMakeFiles/example5.dir/build.make src/CMakeFiles/example5.dir/build
.PHONY : example5/fast

#=============================================================================
# Target rules for targets named example4

# Build rule for target.
example4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example4
.PHONY : example4

# fast build rule for target.
example4/fast:
	$(MAKE) -f src/CMakeFiles/example4.dir/build.make src/CMakeFiles/example4.dir/build
.PHONY : example4/fast

#=============================================================================
# Target rules for targets named example2

# Build rule for target.
example2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example2
.PHONY : example2

# fast build rule for target.
example2/fast:
	$(MAKE) -f src/CMakeFiles/example2.dir/build.make src/CMakeFiles/example2.dir/build
.PHONY : example2/fast

#=============================================================================
# Target rules for targets named example6

# Build rule for target.
example6: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example6
.PHONY : example6

# fast build rule for target.
example6/fast:
	$(MAKE) -f src/CMakeFiles/example6.dir/build.make src/CMakeFiles/example6.dir/build
.PHONY : example6/fast

#=============================================================================
# Target rules for targets named play

# Build rule for target.
play: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 play
.PHONY : play

# fast build rule for target.
play/fast:
	$(MAKE) -f src/CMakeFiles/play.dir/build.make src/CMakeFiles/play.dir/build
.PHONY : play/fast

#=============================================================================
# Target rules for targets named soxi

# Build rule for target.
soxi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 soxi
.PHONY : soxi

# fast build rule for target.
soxi/fast:
	$(MAKE) -f src/CMakeFiles/soxi.dir/build.make src/CMakeFiles/soxi.dir/build
.PHONY : soxi/fast

#=============================================================================
# Target rules for targets named gsm

# Build rule for target.
gsm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gsm
.PHONY : gsm

# fast build rule for target.
gsm/fast:
	$(MAKE) -f libgsm/CMakeFiles/gsm.dir/build.make libgsm/CMakeFiles/gsm.dir/build
.PHONY : gsm/fast

#=============================================================================
# Target rules for targets named lpc10

# Build rule for target.
lpc10: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lpc10
.PHONY : lpc10

# fast build rule for target.
lpc10/fast:
	$(MAKE) -f lpc10/CMakeFiles/lpc10.dir/build.make lpc10/CMakeFiles/lpc10.dir/build
.PHONY : lpc10/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tags"
	@echo "... libsox"
	@echo "... sox"
	@echo "... rec"
	@echo "... sox_sample_test"
	@echo "... example0"
	@echo "... example3"
	@echo "... example1"
	@echo "... example5"
	@echo "... example4"
	@echo "... example2"
	@echo "... example6"
	@echo "... play"
	@echo "... soxi"
	@echo "... gsm"
	@echo "... lpc10"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

